[package]
name = "bezier"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_prototype_lyon = { git = "https://github.com/rparrett/bevy_prototype_lyon", branch = "fix-dynamic-examples" }
#togo = "0.4.1"
